### ISSUE TITLE
Windows 10 Errors

### ISSUE THREAD

**Issue by wendeborn8** [afeinstein20/eleanor#222]
I am having some trouble running the command

`star = eleanor.multi_sector(tic = 38846515,  sectors = 'all')`

After printing the following:

```
Found star in Sector(s) 1 2 3 4 5 6 7 8 9 10 11 12 13 27 28 29 30 31
C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
INFO: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_bkg.fits with expected size 78955200. [astroquery.query]
INFO: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc.fits with expected size 158022720. [astroquery.query]
INFO: Found cached file ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0001-4-1-cal-0902-1078_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0001-4-1_tess_v2_pm.txt with expected size 237847. [astroquery.query]
C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0002/4-1/hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_bkg.fits to ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_bkg.fits ... [Done]
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0002/4-1/hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_pc.fits to ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_pc.fits ... [Done]
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0002/4-1/hlsp_eleanor_tess_ffi_postcard-s0002-4-1_tess_v2_pm.txt to ./mastDownload\HLSP\hlsp_eleanor_tess_ffi_postcard-s0002-4-1-cal-1490-0646_tess_v2_pc\hlsp_eleanor_tess_ffi_postcard-s0002-4-1_tess_v2_pm.txt ... [Done]
C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\ffi.py:40: UserWarning: couldn't find pointing model
  warnings.warn("couldn't find pointing model")
Downloading URL https://mast.stsci.edu/tesscut/api/v0.1/astrocut?ra=68.95970833333332&dec=-64.02703611111112&y=31&x=31&units=px&sector=3 to .\tesscut_20210128115543.zip ... [Done]
Inflating...
```

I get this error:

```
Traceback (most recent call last):`

  File "C:\Users\jwend\Documents\Python\QueryScripts\TESS.py", line 8, in <module>
    star = eleanor.multi_sectors(tic = 38846515, sectors = 'all')

  File "C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\source.py", line 75, in multi_sectors
    star = Source(tic=tic, gaia=gaia, coords=coords, sector=int(s), tc=tc, local=local, post_dir=post_dir, pm_dir=pm_dir,

  File "C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\source.py", line 257, in __init__
    Update(sector=self.sector)

  File "C:\Users\jwend\anaconda3\lib\site-packages\eleanor-2.0.1-py3.8.egg\eleanor\update.py", line 130, in __init__
    os.remove(manifest['Local Path'][0])

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.\\tess-s0002-4-1_68.959708_-64.027036_31x31_astrocut.fits'
```

The error occurs no matter what object name I choose, though what gets printed (i.e. how far along it gets) varies form object to object. It does not occur when using eleanor.Source, only multi_sectors. Interestingly, the error persists even for objects that are found only in one sector, like 'V883 Ori".

For reference, I am using Spyder 4.1.5 on Windows 10, Python version 3.8.3. To get around the tensorflow version errors in installing eleanor, I edited the 'setup.py' file and removed the tensorflow dependency, but nothing else. I then installed eleanor using "python setup.py install". As far as I'm aware, I do not have other instances of Python open or anything else that would be simultaneously using these files.

**Comment by benmontet** [comment]
Hey,

This is the same error as #219, which I think we may have just sorted. The github version has what I believe to be the fix to update.py that will make this work properly, can you please grab that version (or replace the `update.py` file in your `eleanor.__path__` with the version on the github) and see if that works for you?

**Comment by wendeborn8** [comment]
Apologies. I didn't see the second half of that issue report. But replacing the update.py file seems to have fixed it. Thank you.

**Comment by benmontet** [comment]
Good, glad it’s sorted for you!
