### ISSUE TITLE
"Connection timed out" error while running eleanor.

### ISSUE THREAD

**Issue by Alakay2** [afeinstein20/eleanor#273]
Hi,
I am following eleanor quickstart tutorials after installation.  After importing eleanor, when I use "**eleanor.Update(sector=27)**", it created the directory and downloaded the "**cadences_s0027, cbv_components, quality and target_s0027.**" files. But it's showing error when I use the next command "**star = eleanor.Source(tic=38846515, sector=1)**". I am getting following message:

>>> star = eleanor.Source(tic=38846515, sector=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/source.py", line 248, in __init__
    self.gaia = gaia_from_coords(self.coords)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/mast.py", line 183, in gaia_from_coords
    gaia = crossmatch_by_position(coords, 0.01, 'Mast.GaiaDR3.Crossmatch')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/mast.py", line 137, in crossmatch_by_position
    headers, outString = mastQuery(request)
                         ^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/mast.py", line 52, in mastQuery
    conn.request('POST', '/api/v0/invoke', 'request='+requestString, headers)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1343, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1389, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1338, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1097, in _send_output
    self.send(msg)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1041, in send
    self.connect()
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1477, in connect
    super().connect()
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1007, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

I tried multiple times but getting the same error (I am using institute proxy setting but also tried with other network). Do you have any suggestions?

**Comment by exo-pt** [comment]
Hi,

I see your error is a connection time out from a MAST query, and the MAST services were offline for maintenance during all the weekend,
If you try again, it may work.

**Comment by Alakay2** [comment]
> Hi,
> 
> I see your error is a connection time out from a MAST query, and the MAST services were offline for maintenance during all the weekend, If you try again, it may work.

Thanks @exo-pt , I tried again but got the same error. Is there any way to confirm if MAST services are online again?

**Comment by Alakay2** [comment]
Still getting the same error. For TGLC, eleanor and using astroquery with gaia, getting same error. Suggestions by anyone???
