### ISSUE TITLE
invalid index to scalar variable in targetdata.py

### ISSUE THREAD

**Issue by Hawkmoon95** [afeinstein20/eleanor#274]
Hello, I am running into what seems like a standard python error but nothing I have tried fixes it. 
My code is:
```
import eleanor
import numpy as np
import matplotlib.pyplot as plt

star = eleanor.Source(gaia=1015028491488955776, sector=47, tc=True);
print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
     .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))
data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)
```
And the error:
```
Found TIC 802157828 (Gaia 1015028491488955776), with TESS magnitude 18.2657, RA 131.81740452100803, and Dec 48.70567391553705
/opt/anaconda3/lib/python3.11/site-packages/eleanor/targetdata.py:857: RuntimeWarning: invalid value encountered in divide
WARNING: Input data contains invalid values (NaNs or infs), which were automatically clipped. [astropy.stats.sigma_clipping]
Traceback (most recent call last):

  File /opt/anaconda3/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Desktop/TESS/Eleanor.py:17
    data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True)

  File /opt/anaconda3/lib/python3.11/site-packages/eleanor/targetdata.py:249 in __init__

  File /opt/anaconda3/lib/python3.11/site-packages/eleanor/targetdata.py:925 in psf_lightcurve

IndexError: invalid index to scalar variable.
```
if I set do_psf=False, then the error goes away, but naturally I need the psf. Both the pip version and the GitHub version of Eleanor produce this error.

**Comment by Alakay2** [comment]
Hi ,

I am getting the same kind of error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/targetdata.py", line 249, in __init__
    self.psf_lightcurve()
  File "/home/anaconda3/envs/eureka/lib/python3.12/site-packages/eleanor/targetdata.py", line 927, in psf_lightcurve
    modepix = np.where(dsum == mode(dsum, axis=None)[0][0])
                               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.

Can you suggest some fix for this?

Regards,
Alax
