### ISSUE TITLE
Cannot query target with eleanor.Source

### ISSUE THREAD

**Issue by ajustesen** [afeinstein20/eleanor#83]
None of the three methods in the tutorial for querying a star works. I get the following errors:

```python
>>> star = eleanor.Source(tic=38846515, sector=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anders/Uni/software/eleanor/eleanor/source.py", line 161, in __init__
    self.coords, self.tess_mag, self.tic_version = coords_from_tic(self.tic)
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 151, in coords_from_tic
    ticData = Catalogs.query_object('tic'+str(tic), radius=.0001, catalog="TIC")
  File "/home/anders/miniconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/astroquery/mast/core.py", line 1922, in query_object_async
    coordinates = self._resolve_object(objectname)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/astroquery/mast/core.py", line 866, in _resolve_object
    raise ResolverError("Could not resolve {} to a sky position.".format(objectname))
astroquery.exceptions.ResolverError: Could not resolve tic38846515 to a sky position.
```

```python
>>> star = eleanor.Source(coords=(68.959732, -64.02704), sector=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anders/Uni/software/eleanor/eleanor/source.py", line 153, in __init__
    self.tic, self.tess_mag, sep, self.tic_version = tic_from_coords(self.coords)
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 167, in tic_from_coords
    tess = crossmatch_by_position(coords, 0.01, 'Mast.Tic.Crossmatch')
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 138, in crossmatch_by_position
    return jsonTable(json.loads(outString))
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 77, in jsonTable
    for col,atype in [(x['name'],x['type']) for x in jsonObj['fields']]:
KeyError: 'fields'
```

```python
>>> star = eleanor.Source(gaia=4675352109658261376, sector=1)
Created TAP+ (v1.0.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: False
	Port: 80
	SSL Port: 443
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anders/Uni/software/eleanor/eleanor/source.py", line 158, in __init__
    self.tic, self.tess_mag, sep, self.tic_version = tic_from_coords(self.coords)
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 167, in tic_from_coords
    tess = crossmatch_by_position(coords, 0.01, 'Mast.Tic.Crossmatch')
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 138, in crossmatch_by_position
    return jsonTable(json.loads(outString))
  File "/home/anders/Uni/software/eleanor/eleanor/mast.py", line 77, in jsonTable
    for col,atype in [(x['name'],x['type']) for x in jsonObj['fields']]:
KeyError: 'fields'
```

The object `jsonObj` is simply a dictionary with the content:
`{'status': 'ERROR', 'msg': 'Cannot open database "TESSINPUTCATALOG_V80" requested by the login. The login failed.\r\nLogin failed for user \'webaccess\'.'}`

I am using eleanor 0.1.8 with Python 3.7.3. The errors are perhaps related to the new version of TIC, TICv8, that was recently placed on MAST?

**Comment by afeinstein20** [comment]
Hi @ajustesen ! This might have been due to brief MAST downtime recently. I just tried eleanor.Source(tic= 38846515, sector=1) and it works just fine now. Give it a go and let me know if you have any additional issues!

**Comment by ajustesen** [comment]
Thanks, everything works now so it must have been downtime. I was using the MAST web portal so MAST was not down entirely (that's probably why I didn't get timeouts), but it seems that the API access must have been down. Thanks!
